<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'create badge label hint' => 'Selecting one of the labels defined in the app logic description allows to create Transaction and Callback Badges. Leaving this field blank (or selecting the option `no label`) allows the creation of a Task Badge. A Task Badge can not be modified into a different one and viceversa.',
    'Badge successfully deleted.' => '',
    'Callback' => '',
    'Could not create badge.' => '',
    'Could not delete badge.' => '',
    'Create a badge' => '',
    'Delete badge' => '',
    'Incentive Serveer ID' => '',
    'Incentive Server ID' => '',
    'Label' => '',
    'Name, Description' => '',
    'No label' => '',
    'Select label ...' => '',
    'Task' => '',
    'The badge you are trying to delete does not exist.' => '',
    'This is a task badge, it is not possible to select a label.' => '',
    'Transaction' => '',
    'Type' => '',
    'Update badge' => '',
    'WARNING - Operations are available only for apps with status In Develpment.' => '',
    'No transaction label' => '@@@@',
    'Select transaction label ...' => '@@@@',
    'This is a task badge, it is not possible to select a transaction label.' => '@@@@',
    'Transaction label' => '@@@@',
];