<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Λογαριασμός',
    'Account & Profile' => 'Λογαριασμός & Προφίλ ',
    'Add a developers to the app' => 'Προσθέστε προγραμματιστές στην εφαρμογή',
    'All Rights reserved' => 'Ολα τα δικαιώματα διατηρούνται',
    'Apps' => 'Εφαρμογές',
    'Authorise' => 'Εξουσιοδότηση',
    'Change password' => 'Αλλαγή κωδικού',
    'Conversational Connector' => 'Σύνδεσμος συνομιλίας',
    'Create new app' => 'Δημιουργία νέας εφαρμογής',
    'Developer' => 'Προγραμματιστής',
    'Email' => 'Email',
    'Error' => 'Λάθος',
    'Female' => 'Θυληκο',
    'Home' => 'Αρχή',
    'In another way' => 'Κανένα από αυτά',
    'Log in' => 'Σύνδεση',
    'Login' => 'Σύνδεση',
    'Logout' => 'Αποσύνδεση',
    'Male' => 'Αρσενικός',
    'Manage developers' => 'Διαχείριση προγραμματιστών',
    'My Apps' => 'Οι εφαρμογές μου',
    'Non-binary' => 'Μη δυαδικό φύλο',
    'OAuth2 configuration' => 'Διαμόρφωση OAuth2',
    'Password' => 'Κωδικός πρόσβασης',
    'Prefer not to say' => 'Προτιμώ να μην πω',
    'Process succefully completed' => 'Η διαδικασία ολοκληρώθηκε με επιτυχία',
    'Profile' => 'Προφίλ',
    'Request password reset' => 'Αίτημα επαναφοράς κωδικού πρόσβασης',
    'Resend verification email' => 'Επαναποστολή μηνύματος επιβεβαίωσης',
    'Reset password' => 'Επαναφορά του κωδικού πρόσβασής σας',
    'Save' => 'Αποθήκευση',
    'Send' => 'Αποστολή',
    'Sign up' => 'Εγγραφείτε',
    'Signup' => 'Εγγραφείτε',
    'Update app' => 'Ενημέρωση της εφαρμογής',
    'Username' => 'Όνομα χρήστη',
    'Username or Email' => 'Ονομα χρήστη ή διεύθυνση ηλεκτρονικού ταχυδρομείου',
    'Yes' => 'Nαι',
    'add' => 'Προσθήκη',
    'close' => 'κλείσιμο',
    'continue' => 'συνέχεια',
    'delete' => 'διαγραφή',
    'delete developer' => 'διαγραφή προγραματιστή',
    'edit' => 'Επεξεργασία',
    'edit app' => 'Επεξεργασία εφαρμογής',
    'manage developers' => 'Διαχείριση προγραμματιστών',
    'view' => 'προβολή',
    'App Details' => '',
    'Apps logic' => '',
    'Are you sure you want to proceed?' => '',
    'Badges' => '',
    'Community Norms' => '',
    'Create date' => '',
    'Create new app logic' => '',
    'Delete app' => '',
    'Delete app logic' => '',
    'Details' => '',
    'Developers' => '',
    'Enabled Apps' => '',
    'My apps' => '',
    'Name' => '',
    'Settings' => '',
    'Stats' => '',
    'Task type ID' => '',
    'Update app logic' => '',
    'Update community' => '',
    'Update date' => '',
    'You are not authorised to perform this action.' => '',
    'cancel' => '',
    'edit app logic' => '',
    'manage' => '',
    'owner' => '',
];
