<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About WeNet' => 'Σχετικά με το WeNet',
    'About WeNet Hub' => 'Σχετικά με το Wenet Hub',
    'Discover more' => 'Ανακαλύψτε περισσότερα',
    'about text' => 'Η διαφορετικότητα είναι μέρος της καθημερινότητάς μας. Η τεχνολογία, παρά την εξέλιξή της, εξακολουθεί να αγωνίζεται όταν πρόκειται να βοηθήσει στην ανάπτυξη και διατήρηση κοινωνικών σχέσεων που υπερβαίνουν το γεωγραφικό και πολιτιστικό υπόβαθρο.',
    'about text 2' => 'Ο στόχος είναι να συνδεθούν άνθρωποι που μπορούν να βοηθήσουν ο ένας τον άλλον και το κλειδί είναι να επωφεληθούν από τη διαφορετικότητά τους.',
    'hub text' => 'Συνδεθείτε για να ανακαλύψετε και να χρησιμοποιήσετε όλες τις εξαιρετικές εφαρμογές WeNet.',
];
