<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account info' => 'Πληροφορίες λογαριασμού',
    'Become a developer' => 'Γίνετε προγραμματιστής',
    'Birthdate' => 'Ημερομηνια γεννησης',
    'Contact the service desk reporting the following data' => 'Contact the service desk reporting the following data',
    'Could not update profile.' => 'Η ενημέρωση του προφίλ απέτυχε.',
    'Developer' => 'Προγραμματιστής',
    'Do you want to delete your account?' => 'Do you want to delete your account?',
    'Email' => 'Ηλεκτρονική Διεύθυνση',
    'Error upgrading your profile to a developer, try later.' => 'Σφάλμα κατά την ενημέρωση του προφίλ σας στον προγραμματιστή, δοκιμάστε ξανά αργότερα.',
    'Error visualizing your profile, try later.' => 'Σφάλμα κατά την προβολή του προφίλ σας, δοκιμάστε ξανά αργότερα.',
    'Example +393401234567 ...' => 'Παράδειγμα +306984245384 ...',
    'First name' => 'Όνομα',
    'Gender' => 'Φύλο',
    'Language' => 'Γλώσσα',
    'Last name' => 'Επίθετο',
    'Middle name' => 'Μεσαίο όνομα',
    'Nationality' => 'Ιθαγένεια',
    'Phone number' => 'Τηλεφωνικό νούμερο',
    'Phone number format is not correct. Example: +393401234567' => 'Η μορφή του αριθμού τηλεφώνου δεν είναι σωστή. Παράδειγμα: +306984245384',
    'Prefix name' => 'πρόθεμα ονόματος',
    'Profile successfully updated.' => 'Το προφίλ ενημερώθηκε με επιτυχία.',
    'Remember to fill in your' => 'Θυμηθείτε να ολοκληρώσετε το δικό σας',
    'Select gender ...' => 'Επιλέξτε φύλο ...',
    'Select language ...' => 'Επιλέξτε γλώσσα ...',
    'Select nationality ...' => 'Επιλέξτε εθνικότητα ...',
    'Send an email to our service desk' => 'Send an email to our service desk',
    'Suffix name' => 'Επίθημα ονόματος',
    'User ID' => 'Ταυτότητα χρήστη',
    'Username' => 'Όνομα χρήστη',
    'delete_account' => 'As soon as we process your request, your account, your profile, the association with all the apps you have used and the related data will be deleted. <br>If you are a developer, all the apps you own will also be deleted. If you are only a developer, but not an app owner, these will be kept.<br><br>Once cancelled, you will receive a confirmation e-mail.',
    'explanation' => 'Θέλετε να δημιουργήσετε τη δική σας εφαρμογή; Γίνετε προγραμματιστής και ξεκινήστε να δημιουργείτε το δικό σας! <br> Θυμηθείτε, για να γίνετε προγραμματιστής πρέπει να ορίσετε το όνομα, το επώνυμο και την ημερομηνία γέννησής σας στο προφίλ σας.',
    'profile' => 'Προφίλ',
    'delete_account_subject' => 'specifing in the subject [WeNet account deletion].',
];
