<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => 'Ελέγξτε το email σας για περαιτέρω οδηγίες. Σε περίπτωση προβλημάτων, ελέγξτε τον φάκελο SPAM.',
    'New password saved.' => 'Αποθηκεύτηκε νέος κωδικός πρόσβασης.',
    'Sorry, we are unable to reset password for the provided email address.' => 'Λυπούμαστε, δεν μπορούμε να επαναφέρουμε τον κωδικό πρόσβασης για τη διεύθυνση email που καταχωρίσατε.',
    'WeNet HUB - Reset password' => 'WeNet HUB - Επαναφορά κωδικού πρόσβασης',
    'WeNet HUB - Verify your email' => 'WeNet HUB - Ελέγξτε το email σας',
];
