<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best,' => 'Καλύτερα',
    'Check your email for further instructions.' => 'Ελέγξτε το email σας για περαιτέρω οδηγίες. Σε περίπτωση προβλημάτων, ελέγξτε το φάκελο SPAM.',
    'Follow the link below to reset your password:' => 'Ακολουθήστε τον παρακάτω σύνδεσμο για να επαναφέρετε τον κωδικό πρόσβασής σας:',
    'Follow the link below to verify your email:' => 'Ακολουθήστε τον παρακάτω σύνδεσμο για να επαληθεύσετε το email σας:',
    'Hello ' => 'Γεια σας',
    'If you forgot your password you can' => 'Εάν ξεχάσατε τον κωδικό πρόσβασής σας, μπορείτε',
    'Need new verification email?' => 'Χρειάζεστε νέο email επαλήθευσης;',
    'Password does not match.' => 'Οι κωδικοί πρόσβασης δεν ταιριάζουν.',
    'Password successfully changed.' => 'Ο κωδικός άλλαξε επιτυχώς.',
    'Please choose your new password' => 'Επιλέξτε τον νέο σας κωδικό πρόσβασης',
    'Please fill out the following fields to login' => 'Συμπληρώστε τα παρακάτω πεδία για να συνδεθείτε',
    'Please fill out the following fields to signup' => 'Συμπληρώστε τα παρακάτω πεδία για να εγγραφείτε',
    'Please fill out your email. A link to reset password will be sent there' => 'Παρακαλώ συμπληρώστε το email σας. Θα σταλεί ένας σύνδεσμος για την επαναφορά του κωδικού πρόσβασής σας. Συμπληρώστε το email σας. Εκεί θα σταλεί ένας σύνδεσμος για την επαναφορά του κωδικού πρόσβασής σας',
    'Please fill out your email. A verification email will be sent there' => 'Παρακαλώ συμπληρώστε το email σας. Εκεί θα σταλεί ένα email επαλήθευσης.',
    'Remember me' => 'Θυμήσου με',
    'Repeat password' => 'επανάληψη κωδικού πρόσβασης',
    'Resend' => 'Αποστολή ξανά',
    'Reset password' => 'Επαναφορά του κωδικού πρόσβασής σας',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Λυπούμαστε, δεν μπορούμε να στείλουμε ξανά το μήνυμα ηλεκτρονικού ταχυδρομείου επαλήθευσης για τη διεύθυνση ηλεκτρονικού ταχυδρομείου που παρέχεται.',
    'Sorry, we are unable to verify your account with provided token.' => 'Λυπούμαστε, δεν μπορούμε να επαληθεύσουμε τον λογαριασμό σας με το παρεχόμενο διακριτικό.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Ευχαριστούμε για την εγγραφή σας. Ελέγξτε τα εισερχόμενά σας για το email επαλήθευσης. Σε περίπτωση προβλημάτων, ελέγξτε το φάκελο SPAM.',
    'The WeNet HUB Team' => 'Η ομάδα WeNet HUB',
    'Verify account' => 'Επιβεβαιώστε τον Λογαριασμό',
    'Your email has been confirmed!' => 'Το email σας επιβεβαιώθηκε!',
    'create an account' => 'Δημιουργία λογαριασμού',
    'reset it' => 'Επαναφορά',
];
