image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - apk add --update bash wget ca-certificates openssl git tar openssh-client curl
  - docker login registry.u-hopper.com -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - push
  - trigger-deploy

build_dev:
  stage: build
  script:
    - apk add --update curl php7 php7-phar php7-json php7-iconv php7-openssl
    - curl --show-error --silent https://getcomposer.org/installer | php
    - ./create_docker_image -si
  artifacts:
    paths:
      - hub_image.tar.gz
    expire_in: 1 day
  only:
    - develop

push_dev:
  stage: push
  script:
    - docker load -i hub_image.tar.gz
    - docker push registry.u-hopper.com/wenet/hub:latest
  dependencies:
    - build_dev
  only:
    - develop

trigger-deploy_dev:
   stage: trigger-deploy
   script:
     - curl --request POST --form "token=${CI_DEPLOY_TOKEN}" --form ref=master --form "variables[DEPLOY_DEV]=1" https://lab.u-hopper.com/api/v4/projects/29/trigger/pipeline
   dependencies:
     - push_dev
     - build_dev
   only:
      - develop

build_prod:
  stage: build
  script:
    - apk add --update curl php7 php7-phar php7-json php7-iconv php7-openssl
    - curl --show-error --silent https://getcomposer.org/installer | php
    - ./create_docker_image -si $CI_COMMIT_TAG
  artifacts:
    paths:
      - hub_image.tar.gz
    expire_in: 1 day
  only:
    - triggers
    - ${RELEASE_TAG}

push_prod:
  stage: push
  script:
    - docker load -i hub_image.tar.gz
    - docker push registry.u-hopper.com/wenet/hub:$CI_COMMIT_TAG
  dependencies:
    - build_prod
   only:
      - triggers
      - ${RELEASE_TAG}

trigger-deploy_prod:
   stage: trigger-deploy
   script:
     - curl --request POST --form "token=${CI_DEPLOY_TOKEN}" --form ref=${RELEASE_TAG} --form "variables[DEPLOY_PROD]=1" https://lab.u-hopper.com/api/v4/projects/29/trigger/pipeline
   dependencies:
     - push_prod
     - build_prod
   only:
      - triggers
      - ${RELEASE_TAG}
