image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - apk add --update bash wget ca-certificates openssl git tar openssh-client
  - apk add ansible ansible-lint
  - mkdir /secret
  - echo "$GITLAB_SSH_KEY" > /secret/ansible.key
  - echo "[deploy_target]" > /secret/inventory
  - echo "${DEPLOYMENT_SERVER_IP} ansible_ssh_private_key_file=/secret/ansible.key ansible_user=gitlab" >> /secret/inventory
  - chmod 400 /secret/ansible.key
  - export ANSIBLE_HOST_KEY_CHECKING=False

  - docker login registry.u-hopper.com -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - push
  - deploy

build_dev:
  stage: build
  script:
    - apk add --update curl php7
    - curl --show-error --silent https://getcomposer.org/installer | php
    - php composer.phar install # --no-dev
    - ./create_docker_image -s
  artifacts:
    paths:
      - hub_image.tar.gz
    expire_in: 1 day
  # only:
  #   - develop

push_dev:
  stage: push
  script:
    - docker load -i hub_image.tar.gz
    - docker push registry.u-hopper.com/wenet/hub:latest
  dependencies:
    - build_dev
  # only:
  #   - develop

deploy_dev:
   stage: deploy
   script:
     - ansible-playbook --user gitlab --inventory /secret/inventory ansible/deploy-test.yml
   dependencies:
     - push_dev
     - build_dev
   environment:
     name: testing
     url: https://wenet.u-hopper.com/dev/hub/frontend/
   # only:
   #    - develop
