---

- name: Setup project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: yii2
    project_path: .
    project_features:
      - docker
      - ci_cd
    docker_registry: docker.io
    docker_image_name: internetofus/hub
  roles:
    - uh.project_template
