<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'filter_platform' => 'Platforms',
    'filter_tags' => 'Tags',
    'App ID' => '',
    'Assistance' => '',
    'Bot Username' => '',
    'Created At' => '',
    'Creator' => '',
    'Description' => '',
    'Disconnect my account' => '',
    'Message Callback Url' => '',
    'Metadata' => '',
    'Name' => '',
    'Owner ID' => '',
    'Social' => '',
    'Status' => '',
    'Telegram' => '',
    'Telegram ID' => '',
    'There is a problem with the Telegram login. Please retry later.' => '',
    'There is a problem with the Telegram logout. Please retry later.' => '',
    'Token' => '',
    'Updated At' => '',
    'User ID' => '',
    'all' => '',
    'filters' => '',
];
