<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Account & Profile' => '',
    'Add a developers to the app' => '',
    'All Rights reserved' => '',
    'App Details' => '',
    'Apps' => '',
    'Apps logic' => '',
    'Are you sure you want to proceed?' => '',
    'Authorise' => '',
    'Badges' => '',
    'Change password' => '',
    'Community Norms' => '',
    'Conversational Connector' => '',
    'Create date' => '',
    'Create new app' => '',
    'Create new app logic' => '',
    'Delete app' => '',
    'Delete app logic' => '',
    'Details' => '',
    'Developer' => '',
    'Developers' => '',
    'Email' => '',
    'Enabled Apps' => '',
    'Error' => '',
    'Female' => '',
    'Home' => '',
    'In another way' => '',
    'Log in' => '',
    'Login' => '',
    'Logout' => '',
    'Male' => '',
    'Manage developers' => '',
    'My Apps' => '',
    'My apps' => '',
    'Name' => '',
    'Non-binary' => '',
    'OAuth2 configuration' => '',
    'Password' => '',
    'Prefer not to say' => '',
    'Process succefully completed' => '',
    'Profile' => '',
    'Request password reset' => '',
    'Resend verification email' => '',
    'Reset password' => '',
    'Save' => '',
    'Send' => '',
    'Settings' => '',
    'Sign up' => '',
    'Signup' => '',
    'Stats' => '',
    'Task type ID' => '',
    'Update app' => '',
    'Update app logic' => '',
    'Update community' => '',
    'Update date' => '',
    'Username' => '',
    'Username or Email' => '',
    'Yes' => '',
    'You are not authorised to perform this action.' => '',
    'add' => '',
    'cancel' => '',
    'close' => '',
    'continue' => '',
    'delete' => '',
    'delete developer' => '',
    'edit' => '',
    'edit app' => '',
    'edit app logic' => '',
    'manage' => '',
    'manage developers' => '',
    'owner' => '',
    'view' => '',
];
