<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'about text' => 'Diversity is part of our everyday life. Technology, despite its evolution, still struggles when it comes to helping develop and maintain social relationships that transcend geographical and cultural backgrounds.',
    'about text 2' => 'The goal is connecting people who can help each other, and the key is leveraging their diversity.',
    'hub text' => 'Login to discover and use all the terrific WeNet applications.',
    'About WeNet' => '',
    'About WeNet Hub' => '',
    'Discover more' => '',
    'Notifiche' => '@@@@',
];
