<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Contact the service desk reporting the following data' => 'Contact the service desk reporting the following data',
    'Do you want to delete your account?' => 'Do you want to delete your account?',
    'Send an email to our service desk' => 'Send an email to our service desk',
    'delete_account' => 'As soon as we process your request, your account, your profile, the association with all the apps you have used and the related data will be deleted. <br>If you are a developer, all the apps you own will also be deleted. If you are only a developer, but not an app owner, these will be kept.<br><br>Once cancelled, you will receive a confirmation e-mail.',
    'explanation' => 'Do you want to create your own app? Become a developer and start building your own!<br>Remember, to become developer you should set your first name, last name and birthdate in your profile.',
    'Account info' => '',
    'Become a developer' => '',
    'Birthdate' => '',
    'Could not update profile.' => '',
    'Developer' => '',
    'Email' => '',
    'Error upgrading your profile to a developer, try later.' => '',
    'Error visualizing your profile, try later.' => '',
    'Example +393401234567 ...' => '',
    'First name' => '',
    'Gender' => '',
    'Language' => '',
    'Last name' => '',
    'Middle name' => '',
    'Nationality' => '',
    'Phone number' => '',
    'Phone number format is not correct. Example: +393401234567' => '',
    'Prefix name' => '',
    'Profile successfully updated.' => '',
    'Remember to fill in your' => '',
    'Select gender ...' => '',
    'Select language ...' => '',
    'Select nationality ...' => '',
    'Suffix name' => '',
    'User ID' => '',
    'Username' => '',
    'delete_account_subject' => 'specifing in the subject [WeNet account deletion].',
    'profile' => '',
];
