<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => 'Check your email for further instructions. In case of trouble check the SPAM folder.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Thank you for registration. Please check your inbox for verification email. In case of trouble check the SPAM folder.',
    'Best,' => '',
    'Follow the link below to reset your password:' => '',
    'Follow the link below to verify your email:' => '',
    'Hello ' => '',
    'If you forgot your password you can' => '',
    'Need new verification email?' => '',
    'Password does not match.' => '',
    'Password successfully changed.' => '',
    'Please choose your new password' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to signup' => '',
    'Please fill out your email. A link to reset password will be sent there' => '',
    'Please fill out your email. A verification email will be sent there' => '',
    'Please, accept our Privacy Policy.' => '',
    'Remember me' => '',
    'Repeat password' => '',
    'Resend' => '',
    'Reset password' => '',
    'Sorry, we are unable to resend verification email for the provided email address.' => '',
    'Sorry, we are unable to verify your account with provided token.' => '',
    'The WeNet HUB Team' => '',
    'Verify account' => '',
    'Your email has been confirmed!' => '',
    'create an account' => '',
    'privacy_consent1' => 'I consent to the processing of data for the purposes described in the',
    'privacy_consent2' => 'that I have read and understood.',
    'reset it' => '',
];
