<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Congratulations! You successfully activated the {app_name} application.' => '¡Felicidades! Ha activado correctamente la aplicación {app_name}.',
    'Ooops! Something went wrong while activating the {app_name} application.' => '¡Vaya! Se produjo un error al activar la aplicación {app_name}.',
    'The application {app_name} will be able to' => 'La aplicación {app_name} podrá',
    'access your profile data' => 'acceder a los datos de su perfil',
    'access your public profile info' => 'acceder a la información de su perfil público',
    'cancel' => 'cancelar',
    'write your profile data' => 'escribe los datos de tu perfil',
];
