<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Cuenta',
    'Account & Profile' => 'Cuenta & Perfil',
    'Add a developers to the app' => 'Agregar desarrolladores a la aplicación',
    'All Rights reserved' => 'Todos los derechos reservados',
    'Apps' => 'Aplicaciones',
    'Authorise' => 'Autorizar',
    'Change password' => 'Cambiar la contraseña',
    'Conversational Connector' => 'Conector conversacional',
    'Create new app' => 'Crear nueva aplicación',
    'Developer' => 'Desarrollador',
    'Email' => 'Correo electrónico',
    'Error' => 'Error',
    'Female' => 'Femenino',
    'Home' => 'Inicio',
    'In another way' => 'Ninguno de esos',
    'Log in' => 'Iniciar sesión',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar sesión',
    'Male' => 'Masculino',
    'Manage developers' => 'Administrar desarrolladores',
    'My Apps' => 'Mis aplicaciones',
    'Non-binary' => 'Género no binario',
    'OAuth2 configuration' => 'Configuración de OAuth2',
    'Password' => 'Contraseña',
    'Prefer not to say' => 'Prefiero no decirlo',
    'Process succefully completed' => 'Proceso completado con éxito',
    'Profile' => 'Perfil',
    'Request password reset' => 'Solicitar restablecimiento de contraseña',
    'Resend verification email' => 'Reenviar correo electrónico de verificación',
    'Reset password' => 'Restablecer la contraseña',
    'Save' => 'Guardar',
    'Send' => 'Enviar',
    'Sign up' => 'Registrarse',
    'Signup' => 'Registrarse',
    'Update app' => 'Actualizar aplicación',
    'Username' => 'Nombre de usuario',
    'Username or Email' => 'Nombre de usuario o correo electrónico',
    'Yes' => 'Sí',
    'add' => 'agregar',
    'close' => 'cerrar',
    'continue' => 'continuar',
    'delete' => 'eliminar',
    'delete developer' => 'eliminar desarrollador',
    'edit' => 'editar',
    'edit app' => 'editar aplicación',
    'manage developers' => 'Administrar desarrolladores',
    'view' => 'ver',
    'Apps logic' => '',
    'Are you sure you want to proceed?' => '',
    'Create date' => '',
    'Create new app logic' => '',
    'Delete app' => '',
    'Delete app logic' => '',
    'Details' => '',
    'Developers' => '',
    'Enabled Apps' => '',
    'My apps' => '',
    'Name' => '',
    'Settings' => '',
    'Stats' => '',
    'Task type ID' => '',
    'Update app logic' => '',
    'Update date' => '',
    'You are not authorised to perform this action.' => '',
    'cancel' => '',
    'edit app logic' => '',
    'manage' => '',
    'Other' => '@@Otro@@',
];
