<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About WeNet' => 'Sobre WeNet',
    'About WeNet Hub' => 'Sobre Wenet Hub',
    'Discover more' => 'Descubrir más',
    'about text' => 'La diversidad forma parte de nuestra vida diaria. La tecnología, a pesar de su evolución, todavía lucha cuando se trata de ayudar a desarrollar y mantener relaciones sociales que trascienden los antecedentes geográficos y culturales.',
    'about text 2' => 'El objetivo es conectar a personas que puedan ayudarse entre sí, y la clave es aprovechar su diversidad.',
    'hub text' => 'Inicie sesión para descubrir y utilizar todas las fantásticas aplicaciones de WeNet.',
    'Notifiche' => '',
];
