<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account info' => 'Información de la cuenta',
    'Become a developer' => 'Conviértete en desarrollador',
    'Birthdate' => 'Fecha de nacimiento',
    'Could not update profile.' => 'No se pudo actualizar el perfil.',
    'Developer' => 'Desarrollador',
    'Email' => 'Correo electrónico',
    'Error upgrading your profile to a developer, try later.' => 'Error al actualizar su perfil a desarrollador, inténtelo más tarde.',
    'Error visualizing your profile, try later.' => 'Error al visualizar su perfil, inténtelo más tarde.',
    'Example +393401234567 ...' => 'Ejemplo +393401234567 ...',
    'First name' => 'Primer nombre',
    'Gender' => 'Género',
    'Language' => 'Idioma',
    'Last name' => 'Apellido',
    'Middle name' => 'Segundo nombre',
    'Nationality' => 'Nacionalidad',
    'Phone number' => 'Número de teléfono',
    'Phone number format is not correct. Example: +393401234567' => 'El formato del número de teléfono no es correcto. Ejemplo: +393401234567',
    'Prefix name' => 'Prefijo del nombre',
    'Profile successfully updated.' => 'Perfil actualizado correctamente.',
    'Remember to fill in your' => 'Recuerde completar su',
    'Select gender ...' => 'Seleccione género ...',
    'Select language ...' => 'Seleccione el idioma ...',
    'Select nationality ...' => 'Seleccione la nacionalidad ...',
    'Suffix name' => 'Sufijo del nombre',
    'User ID' => 'ID de usuario',
    'Username' => 'Nombre de usuario',
    'explanation' => '¿Quieres crear tu propia aplicación? ¡Conviértete en desarrollador y comienza a crear el tuyo propio! <br> Recuerda, para convertirte en desarrollador debes establecer tu nombre, apellido y fecha de nacimiento en tu perfil.',
    'profile' => 'perfil',
];
