<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activities' => 'Actividades',
    'Avatar' => 'Avatar',
    'Behaviours' => 'Comportamientos',
    'Birthdate' => 'Fecha de nacimiento',
    'Birthdate: DEPRECATED' => 'Fecha de nacimiento: OBSOLETO',
    'Competences' => '',
    'Conversation' => 'Registro de conversaciones',
    'Conversation logging: DEPRECATED' => 'Registro de conversaciones: OBSOLETO',
    'Data' => 'Datos',
    'Email' => 'Correo electrónico',
    'First name' => 'Primer nombre',
    'First name: DEPRECATED' => 'Primer nombre: OBSOLETO',
    'Gender' => 'Género',
    'Gender: DEPRECATED' => 'Género: OBSOLETO',
    'ID' => 'ID de usuario',
    'ID: DEPRECATED' => 'ID de usuario: OBSOLETO',
    'Language: DEPRECATED' => 'Idioma: OBSOLETO',
    'Last name' => 'Apellido',
    'Last name: DEPRECATED' => 'Apellido: OBSOLETO',
    'Locale' => 'Lugar',
    'Locations' => 'Ubicaciones',
    'Materials' => 'Materiales',
    'Meanings' => 'Significados',
    'Middle name' => 'Segundo nombre',
    'Middle name: DEPRECATED' => 'Segundo nombre: OBSOLETO',
    'Nationality' => 'Nacionalidad',
    'Nationality: DEPRECATED' => 'Nacionalidad: OBSOLETO',
    'Norms' => 'Normas',
    'Occupation' => 'Ocupación',
    'Phone number' => 'Número de teléfono',
    'Phone number: DEPRECATED' => 'Número de teléfono: OBSOLETO',
    'Prefix name' => 'Prefijo del nombre',
    'Prefix name: DEPRECATED' => 'Prefijo del nombre: OBSOLETO',
    'Relationships' => 'Relaciones',
    'Suffix name' => 'Sufijo del nombre',
    'Suffix name: DEPRECATED' => 'Sufijo del nombre: OBSOLETO',
    'Write data feed: DEPRECATED' => 'Escribir fuente de datos: OBSOLETO',
];
