<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best,' => 'Mejor',
    'Check your email for further instructions.' => 'Revise su correo electrónico para obtener más instrucciones. En caso de problemas, consulte la carpeta SPAM.',
    'Follow the link below to reset your password:' => 'Siga el enlace a continuación para restablecer su contraseña:',
    'Follow the link below to verify your email:' => 'Siga el enlace a continuación para verificar su correo electrónico:',
    'Hello ' => 'Hola ',
    'If you forgot your password you can' => 'Si olvidó su contraseña, puede',
    'Need new verification email?' => '¿Necesita un nuevo correo electrónico de verificación?',
    'Password does not match.' => 'Las contraseñas no coinciden.',
    'Password successfully changed.' => 'Contraseña cambiada correctamente.',
    'Please choose your new password' => 'Por favor seleccione su nueva contraseña',
    'Please fill out the following fields to login' => 'Por favor, rellene los siguientes campos para iniciar sesión',
    'Please fill out the following fields to signup' => 'Por favor complete los siguientes campos para registrarse',
    'Please fill out your email. A link to reset password will be sent there' => 'Por favor complete su correo electrónico. Allí se enviará un enlace para restablecer la contraseña',
    'Please fill out your email. A verification email will be sent there' => 'Por favor complete su correo electrónico. Allí se enviará un correo electrónico de verificación.',
    'Remember me' => 'Recuérdame',
    'Repeat password' => 'Repetir la contraseña',
    'Resend' => 'Reenviar',
    'Reset password' => 'Restablecer la contraseña',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Lo sentimos, no podemos reenviar el correo electrónico de verificación para la dirección de correo electrónico proporcionada.',
    'Sorry, we are unable to verify your account with provided token.' => 'Lo sentimos, no podemos verificar su cuenta con el token proporcionado.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Gracias por registrarse. Por favor revise su bandeja de entrada para ver el correo electrónico de verificación. En caso de problemas, consulte la carpeta SPAM.',
    'The WeNet HUB Team' => 'El equipo de WeNet HUB',
    'Verify account' => 'Verificar Cuenta',
    'Your email has been confirmed!' => '¡Tu correo ha sido confirmado!',
    'create an account' => 'crear una cuenta',
    'reset it' => 'restablecerla',
];
