<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Now you are a developer.' => 'Ahora eres desarrollador.',
    'There is a problem setting your account as developer. Please retry later.' => 'Hay un problema al configurar su cuenta como desarrollador. Vuelva a intentarlo más tarde.',
    'Your profile is incomplete. Complete it ' => 'Tu perfil está incompleto. Completalo',
    'here' => 'aquí',
    'Access to your information and app connection successfully removed.' => '',
    'There is a problem removing the access to your information. Please retry later.' => '',
];
