<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'filter_platform' => 'puppa',
    'Active users for platform' => '',
    'App ID' => '',
    'App successfully deleted.' => '',
    'Assistance' => '',
    'Because there are no platforms available for this app, the app has been automatically setted as "In development" mode.' => '',
    'Become a developer' => '',
    'Bot Username' => '',
    'Categories' => '',
    'Connected platforms' => '',
    'Could not add platform Telegram.' => '',
    'Could not create app.' => '',
    'Could not delete app.' => '',
    'Could not delete platform.' => '',
    'Create a new app' => '',
    'Created At' => '',
    'Creator' => '',
    'Data ingestion' => '',
    'Description' => '',
    'Description cannot be blank.' => '',
    'Detele platform' => '',
    'Disconnect my account' => '',
    'Don\'t forget to send the /setdomain command to @Botfather to link {domain} domain to the bot.' => '',
    'In development' => '',
    'Live' => '',
    'Message Callback Url' => '',
    'Message Callback Url cannot be blank.' => '',
    'Metadata' => '',
    'More info' => '',
    'Name' => '',
    'Open chat' => '',
    'Owner ID' => '',
    'Platform successfully deleted.' => '',
    'Platforms' => '',
    'Select tags ...' => '',
    'Social' => '',
    'Status' => '',
    'Telegram' => '',
    'Telegram ID' => '',
    'There are no apps to display.' => '',
    'There is a problem with the Telegram login. Please retry later.' => '',
    'There is a problem with the Telegram logout. Please retry later.' => '',
    'To authenticate requests, you will need to include the following parameters in the header of each call:' => '',
    'Token' => '',
    'Updated At' => '',
    'User ID' => '',
    'You should enable at least one platform to go live with the app.' => '',
    'add Telegram' => '',
    'all' => '',
    'filter_tags' => '',
    'filters' => '',
];
