<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Congratulations! You successfully activated the {app_name} application.' => 'Congratulazioni! Hai attivato correttamente l\'applicazione {app_name}.',
    'Ooops! Something went wrong while activating the {app_name} application.' => 'Ops! Qualcosa è andato storto durante l\'attivazione dell\'applicazione {app_name}.',
    'The application {app_name} will be able to' => 'L\'applicazione {app_name} sarà in grado di',
    'access your profile data' => 'accedere ai dati del tuo profilo',
    'access your public profile info' => 'accedere alle informazioni del tuo profilo pubblico',
    'cancel' => 'annulla',
    'write your profile data' => 'scrivere i dati del tuo profilo',
];
