<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Account',
    'Account & Profile' => 'Account e profilo',
    'Add a developers to the app' => 'Aggiungi sviluppatori all\'app',
    'All Rights reserved' => 'Tutti i diritti riservati',
    'Apps' => 'App',
    'Authorise' => 'Autorizza',
    'Change password' => 'Cambia password',
    'Conversational Connector' => 'Connettore conversazionale',
    'Create new app' => 'Crea nuova app',
    'Developer' => 'Sviluppatore',
    'Email' => 'Email',
    'Error' => 'Errore',
    'Female' => 'Donna',
    'Home' => 'Home',
    'In another way' => 'Nessuno di questi',
    'Log in' => 'Log in',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Male' => 'Uomo',
    'Manage developers' => 'Gestisci sviluppatori',
    'My Apps' => 'Le mie app',
    'Non-binary' => 'Identità non binaria',
    'OAuth2 configuration' => 'Configurazione OAuth2',
    'Password' => 'Password',
    'Prefer not to say' => 'Preferisco non dirlo',
    'Process succefully completed' => 'Processo completato con successo',
    'Profile' => 'Profilo',
    'Request password reset' => 'Richiedi ripristino password',
    'Resend verification email' => 'Invia nuovamente l\'email di verifica',
    'Reset password' => 'Resetta password',
    'Save' => 'Salva',
    'Send' => 'Invia',
    'Sign up' => 'Iscriviti',
    'Signup' => 'Iscriviti',
    'Update app' => 'Aggiorna app',
    'Username' => 'Username',
    'Username or Email' => 'Username o Email',
    'Yes' => 'Si',
    'add' => 'aggiungi',
    'close' => 'chiudi',
    'continue' => 'continua',
    'delete' => 'elimina',
    'delete developer' => 'elimina sviluppatore',
    'edit' => 'modifica',
    'edit app' => 'modifica app',
    'manage developers' => 'gestisci sviluppatori',
    'view' => 'visualizza',
    'Apps logic' => '',
    'Create date' => '',
    'Create new app logic' => '',
    'Delete app' => '',
    'Delete app logic' => '',
    'Details' => '',
    'Developers' => '',
    'Enabled Apps' => '',
    'My apps' => '',
    'Update app logic' => '',
    'Update date' => '',
    'edit app logic' => '',
    'manage' => '',
    'Other' => '@@Altro@@',
];
