<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About WeNet' => 'WeNet',
    'About WeNet Hub' => 'WeNet Hub',
    'Discover more' => 'Scopri di più',
    'about text' => 'La diversità fa parte della nostra vita quotidiana. La tecnologia, nonostante la sua evoluzione, lotta ancora quando si tratta di aiutare a sviluppare e mantenere relazioni sociali che trascendono i contesti geografici e culturali.',
    'about text 2' => 'L\'obiettivo è connettere persone che possono aiutarsi a vicenda e la chiave è sfruttare la loro diversità.',
    'hub text' => 'Accedi per scoprire e utilizzare tutte le fantastiche applicazioni WeNet.',
];
