<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account info' => 'Info account',
    'Become a developer' => 'Diventa uno sviluppatore',
    'Birthdate' => 'Data di nascita',
    'Could not update profile.' => 'Impossibile aggiornare il profilo.',
    'Developer' => 'Sviluppatore',
    'Email' => 'Email',
    'Error upgrading your profile to a developer, try later.' => 'Errore durante l\'aggiornamento del profilo a sviluppatore, riprova più tardi.',
    'Error visualizing your profile, try later.' => 'Errore durante la visualizzazione del tuo profilo, riprova più tardi.',
    'Example +393401234567 ...' => 'Esempio +393401234567 ...',
    'First name' => 'Nome',
    'Gender' => 'Genere',
    'Language' => 'Lingua',
    'Last name' => 'Cognome',
    'Middle name' => 'Secondo nome',
    'Nationality' => 'Nazionalità',
    'Phone number' => 'Numero di telefono',
    'Phone number format is not correct. Example: +393401234567' => 'Il formato del numero di telefono non è corretto. Esempio: +393401234567',
    'Prefix name' => 'Prefisso del nome',
    'Profile successfully updated.' => 'Profilo aggiornato con successo.',
    'Remember to fill in your' => 'Ricordati di compilare il tuo',
    'Select gender ...' => 'Seleziona genere ...',
    'Select language ...' => 'Seleziona lingua ...',
    'Select nationality ...' => 'Seleziona nazionalità ...',
    'Suffix name' => 'Suffisso del nome',
    'User ID' => 'Id utente',
    'Username' => 'Username',
    'explanation' => 'Vuoi creare la tua app? Diventa uno sviluppatore e inizia a crearne una tua! <br> Ricorda, per diventare sviluppatore devi impostare il tuo nome, cognome e data di nascita nel tuo profilo.',
    'profile' => 'profilo',
];
