<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account info' => '',
    'Become a developer' => '',
    'Birthdate' => '',
    'Could not update profile.' => '',
    'Developer' => '',
    'Email' => '',
    'Error upgrading your profile to a developer, try later.' => '',
    'Error visualizing your profile, try later.' => '',
    'Example +393401234567 ...' => '',
    'First name' => '',
    'Gender' => '',
    'Language' => '',
    'Last name' => '',
    'Middle name' => '',
    'Nationality' => '',
    'Phone number' => '',
    'Phone number format is not correct. Example: +393401234567' => '',
    'Prefix name' => '',
    'Profile successfully updated.' => '',
    'Select gender ...' => '',
    'Select language ...' => '',
    'Select nationality ...' => '',
    'Suffix name' => '',
    'User ID' => '',
    'Username' => '',
    'explanation' => '',
];
