<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => 'Controlla la tua email per ulteriori istruzioni. In caso non ricevessi l\'email, controlla nello SPAM.',
    'New password saved.' => 'Nuova password salvata.',
    'Sorry, we are unable to reset password for the provided email address.' => 'Spiacenti, non siamo in grado di reimpostare la password per l\'indirizzo email fornito.',
    'WeNet HUB - Reset password' => 'WeNet HUB - Reimposta password',
    'WeNet HUB - Verify your email' => 'WeNet HUB - Verifica la tua email',
];
