<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activities' => 'Attività',
    'Avatar' => 'Avatar',
    'Behaviours' => 'Comportamenti',
    'Birthdate' => 'Data di nascita',
    'Birthdate: DEPRECATED' => 'Data di nascita: DEPRECATO',
    'Competences' => 'Competenze',
    'Conversation' => 'Conversazione',
    'Conversation logging: DEPRECATED' => 'Tracciamento della conversazione: DEPRECATO',
    'Data' => 'Dati',
    'Email' => 'Email',
    'First name' => 'Nome',
    'First name: DEPRECATED' => 'Nome: DEPRECATO',
    'Gender' => 'Genere',
    'Gender: DEPRECATED' => 'Genere: DEPRECATO',
    'ID' => 'Id utente',
    'ID: DEPRECATED' => 'Id utente: DEPRECATO',
    'Language: DEPRECATED' => 'Lingua: DEPRECATED',
    'Last name' => 'Cognome',
    'Last name: DEPRECATED' => 'Cognome: DEPRECATO',
    'Locale' => 'Lingua',
    'Locations' => 'Posizioni',
    'Materials' => 'Materiali',
    'Meanings' => 'Significati',
    'Middle name' => 'Secondo nome',
    'Middle name: DEPRECATED' => 'Secondo nome: DEPRECATO',
    'Nationality' => 'Nazionalità',
    'Nationality: DEPRECATED' => 'Nazionalità: DEPRECATO',
    'Norms' => 'Norme',
    'Occupation' => 'Occupazione',
    'Phone number' => 'Numero di telefono',
    'Phone number: DEPRECATED' => 'Numero di telefono: DEPRECATO',
    'Prefix name' => 'Prefisso del nome',
    'Prefix name: DEPRECATED' => 'Prefisso del nome: DEPRECATO',
    'Relationships' => 'Relazioni',
    'Suffix name' => 'Suffisso del nome',
    'Suffix name: DEPRECATED' => 'Suffisso del nome: DEPRECATO',
    'Write data feed: DEPRECATED' => 'Write data feed: DEPRECATO',
];
