<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best,' => 'Un saluto,',
    'Check your email for further instructions.' => 'Controlla la tua email per ulteriori istruzioni.',
    'Follow the link below to reset your password:' => 'Segui il link sottostante per reimpostare la password:',
    'Follow the link below to verify your email:' => 'Segui il link sottostante per verificare la tua email:',
    'Hello ' => 'Ciao',
    'If you forgot your password you can' => 'Se hai dimenticato la password puoi',
    'Need new verification email?' => 'Hai bisogno di una nuova email di verifica?',
    'Password does not match.' => 'La password non corrisponde.',
    'Password successfully changed.' => 'Password cambiata con successo.',
    'Please choose your new password' => 'Scegli la tua nuova password',
    'Please fill out the following fields to login' => 'Si prega di compilare i seguenti campi per effettuare il login',
    'Please fill out the following fields to signup' => 'Si prega di compilare i seguenti campi per registrarsi',
    'Please fill out your email. A link to reset password will be sent there' => 'Compila la tua email. Ti verrà inviata un\'email con il link per reimpostare la password',
    'Please fill out your email. A verification email will be sent there' => 'Compila la tua email. Ti verrà inviata un\'email di verifica',
    'Remember me' => 'Ricordami',
    'Repeat password' => 'Ripeti password',
    'Resend' => 'Re-invia',
    'Reset password' => 'Resetta password',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Spiacenti, non siamo in grado di inviare nuovamente l\'email di verifica per l\'indirizzo email fornito.',
    'Sorry, we are unable to verify your account with provided token.' => 'Spiacenti, non siamo in grado di verificare il tuo account con il token fornito.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Grazie per la registrazione. Controlla la tua casella di posta per l\'email di verifica.',
    'The WeNet HUB Team' => 'il team WeNet HUB',
    'Verify account' => 'Verifica Account',
    'Your email has been confirmed!' => 'La tua email è stata confermata!',
    'create an account' => 'crea un account',
    'reset it' => 'resettarla',
];
