<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Now you are a developer.' => 'Adesso sei uno sviluppatore.',
    'There is a problem setting your account as developer. Please retry later.' => 'Si è verificato un problema durante l\'impostazione del tuo account come sviluppatore. Riprova più tardi',
    'Your profile is incomplete. Complete it ' => 'Il tuo profilo è incompleto. Completalo ',
    'here' => 'qui',
    'Access to your information and app connection successfully removed.' => 'L\'accesso alle tue informazioni e la connessione all\'app sono stati rimossi con successo.',
    'There is a problem removing the access to your information. Please retry later.' => 'Si è verificato un problema durante la rimozione dell\'accesso alle tue informazioni. Riprova più tardi.',
];
