<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Congratulations! You successfully activated the {app_name} application.' => 'Баяр хүргэе! Апп {app_name} амжилттай идэвхжилээ.',
    'Ooops! Something went wrong while activating the {app_name} application.' => 'Ooops! Апп {app_name} идэвхжүүлэхэд алдаа гарлаа.',
    'The application {app_name} will be able to' => 'Аппликэйшн {app_name} боломжтой',
    'access your profile data' => 'өөрийн профайл өгөгдөлд хандах',
    'access your public profile info' => 'өөрийн нийтийн профайл өгөгдөлд хандах',
    'cancel' => 'цуцлах',
    'write your profile data' => 'өөрийн профайл өгөгдлийг бичих',
];
