<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Аккаунт',
    'Account & Profile' => 'Аккаунт ба Профайл',
    'Add a developers to the app' => 'Апп-д хөгжүүлэгчид нэмэх',
    'All Rights reserved' => 'Бүх эрх хуулиар хамгаалагдсан',
    'Apps' => 'Аппууд',
    'Authorise' => 'Эрх олгох',
    'Change password' => 'Нууц үг өөрчлөх',
    'Conversational Connector' => 'Харилцааг холбогч',
    'Create new app' => 'Шинээр апп үүсгэх',
    'Developer' => 'Хөгжүүлэгч',
    'Email' => 'И-мэйл',
    'Error' => 'Алдаа',
    'Female' => 'Эмэгтэй',
    'Home' => 'Гэр',
    'In another way' => 'эдгээрийн аль нь ч биш',
    'Log in' => 'Нэвтрэх',
    'Login' => 'Нэвртэх',
    'Logout' => 'Гарах',
    'Male' => 'Эрэгтэй',
    'Manage developers' => 'Хөгжүүлэгчдийг зохицуулах',
    'My Apps' => 'Миний аппууд',
    'Non-binary' => 'Хоёртын бус хүйс',
    'OAuth2 configuration' => 'OAuth2 тохиргоо',
    'Password' => 'Нууц үг',
    'Prefer not to say' => 'Хэлэхгүй байхыг илүүд үзээрэй',
    'Process succefully completed' => 'Үйл ажиллагаа амжилттай дууслаа',
    'Profile' => 'Профайл',
    'Request password reset' => 'Нууц үг сэргээх хүсэлт гаргах',
    'Resend verification email' => 'Баталгаажуулах и-мэйл дахин илгээх',
    'Reset password' => 'Нууц үг сэргээх',
    'Save' => 'Хадгалах',
    'Send' => 'Илгээх',
    'Sign up' => 'Бүртгүүлэх',
    'Signup' => 'Бүртгүүлэх',
    'Update app' => 'Апп шинэчлэх',
    'Username' => 'Хэрэглэгчийн нэр',
    'Username or Email' => 'Хэрэглэгчийн нэр эсвэл и-мэйл',
    'Yes' => 'Тийм',
    'add' => 'нэмэх',
    'close' => 'хаах',
    'continue' => 'үргэлжлүүлэх',
    'delete' => 'устгах',
    'delete developer' => 'хөгжүүлэгч устгах',
    'edit' => 'засварлах',
    'edit app' => 'апп засварлах',
    'manage developers' => 'хөгжүүлэгчдийг зохицуулах',
    'view' => 'харах',
    'App Details' => '',
    'Apps logic' => '',
    'Are you sure you want to proceed?' => '',
    'Badges' => '',
    'Community Norms' => '',
    'Create date' => '',
    'Create new app logic' => '',
    'Delete app' => '',
    'Delete app logic' => '',
    'Details' => '',
    'Developers' => '',
    'Enabled Apps' => '',
    'My apps' => '',
    'Name' => '',
    'Settings' => '',
    'Stats' => '',
    'Task type ID' => '',
    'Update app logic' => '',
    'Update community' => '',
    'Update date' => '',
    'You are not authorised to perform this action.' => '',
    'cancel' => '',
    'edit app logic' => '',
    'manage' => '',
    'owner' => '',
    'Other' => '@@Бусад@@',
];
