<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About WeNet' => 'Винэтийн тухай',
    'About WeNet Hub' => 'Винэт HUB тухай',
    'Discover more' => 'Илүүг үзэх',
    'about text' => 'Олон талт байдал бол бидний өдөр тутмын амьдралын нэг хэсэг. Технологи хэдийгээр хурдацтай хувьсан өөрчлөгдөж байгаа ч газарзүйн болон соёлын ялгаанаас үүдсэн олон талт нийгмийн холбоог хангахад учир дутмаг хэвээр байна.',
    'about text 2' => 'Винэтийн зорилго бол олон талт байдалд тулгуурлан хүмүүсийг хооронд нь холбох юм.',
    'hub text' => 'Нэвтэрч ороод Винэт аппуудын давуу талуудыг олж мэд.',
    'Notifiche' => '@@@@',
];
