<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'explanation' => 'Өөрийн аппаа үүсгэмээр байна уу? Хөгжүүлэгч болоод аппаа бичиж эхлэ!<br>Хөгжүүлэгч болохын тулд өөрийн профайл дах овог, нэр, төрсөн огноогоо оруулахаа мартуузай.',
    'Account info' => 'Аккаунтын мэдээлэл',
    'Become a developer' => 'Хөгжүүлэгч болох',
    'Birthdate' => 'Төрсөн огноо',
    'Conversation logging' => 'Харилцан ярианы тэмдэглал',
    'Could not update profile.' => 'Профайл шинэчлэх боломжгүй',
    'Developer' => 'Хөгжүүлэгч',
    'Email' => 'Засварлах',
    'Error upgrading your profile to a developer, try later.' => 'Таны профайлыг хөгжүүлэгч болгон шинэчлэх боломжгүй, дараа дахин оролдно уу.',
    'Error visualizing your profile, try later.' => 'Профайлыг харуулах боломжгүй, дараа дахин оролдно уу.',
    'Example +393401234567 ...' => 'Жишээ нь +393401234567 ...',
    'First name' => 'Нэр',
    'Gender' => 'Хүйс',
    'Language' => 'Хэл',
    'Last name' => 'Овог',
    'Middle name' => 'Дундах нэр',
    'Nationality' => 'Үндэс угсаа',
    'Phone number' => 'Утасны дугаар',
    'Phone number format is not correct. Example: +393401234567' => 'Утасны дугаарын хэв буруу байна. Жишээ нь: +393401234567',
    'Prefix name' => 'Урьтал нэр',
    'Profile successfully updated.' => 'Профайл амжилттай шинэчлэгдлээ',
    'Remember to fill in your' => 'Дараах талбарыг оруулна уу',
    'Select gender ...' => 'Хүйс сонгох ...',
    'Select language ...' => 'Хэл сонгох ...',
    'Select nationality ...' => 'Үндэс угсаа сонгох ...',
    'Suffix name' => 'Дагавар нэр',
    'User ID' => 'Хэрэглэгчийн ай-ди',
    'Username' => 'Хэрэглэгчийн нэр',
    'Write data feed' => 'Өгөгдлөөр хангах',
    'profile' => 'профайл',
];
