<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account info' => 'Аккаунтын мэдээлэл',
    'Become a developer' => 'Хөгжүүлэгч болох',
    'Birthdate' => 'Төрсөн огноо',
    'Contact the service desk reporting the following data' => 'Contact the service desk reporting the following data',
    'Could not update profile.' => 'Профайл шинэчлэх боломжгүй',
    'Developer' => 'Хөгжүүлэгч',
    'Do you want to delete your account?' => 'Do you want to delete your account?',
    'Email' => 'Засварлах',
    'Error upgrading your profile to a developer, try later.' => 'Таны профайлыг хөгжүүлэгч болгон шинэчлэх боломжгүй, дараа дахин оролдно уу.',
    'Error visualizing your profile, try later.' => 'Профайлыг харуулах боломжгүй, дараа дахин оролдно уу.',
    'Example +393401234567 ...' => 'Жишээ нь +393401234567 ...',
    'First name' => 'Нэр',
    'Gender' => 'Хүйс',
    'Language' => 'Хэл',
    'Last name' => 'Овог',
    'Middle name' => 'Дундах нэр',
    'Nationality' => 'Үндэс угсаа',
    'Phone number' => 'Утасны дугаар',
    'Phone number format is not correct. Example: +393401234567' => 'Утасны дугаарын хэв буруу байна. Жишээ нь: +393401234567',
    'Prefix name' => 'Урьтал нэр',
    'Profile successfully updated.' => 'Профайл амжилттай шинэчлэгдлээ',
    'Remember to fill in your' => 'Дараах талбарыг оруулна уу',
    'Select gender ...' => 'Хүйс сонгох ...',
    'Select language ...' => 'Хэл сонгох ...',
    'Select nationality ...' => 'Үндэс угсаа сонгох ...',
    'Send an email to our service desk' => 'Send an email to our service desk',
    'Suffix name' => 'Дагавар нэр',
    'User ID' => 'Хэрэглэгчийн ай-ди',
    'Username' => 'Хэрэглэгчийн нэр',
    'delete_account' => 'As soon as we process your request, your account, your profile, the association with all the apps you have used and the related data will be deleted. <br>If you are a developer, all the apps you own will also be deleted. If you are only a developer, but not an app owner, these will be kept.<br><br>Once cancelled, you will receive a confirmation e-mail.',
    'explanation' => 'Өөрийн аппаа үүсгэмээр байна уу? Хөгжүүлэгч болоод аппаа бичиж эхлэ!<br>Хөгжүүлэгч болохын тулд өөрийн профайл дах овог, нэр, төрсөн огноогоо оруулахаа мартуузай.',
    'profile' => 'профайл',
    'delete_account_subject' => 'specifing in the subject [WeNet account deletion].',
];
