<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activities' => 'Үйл явц',
    'Avatar' => 'Аватар',
    'Behaviours' => 'Зан ааш',
    'Birthdate' => 'Төрсөн огноо',
    'Birthdate: DEPRECATED' => 'Төрсөн огноо: ХУУЧИРСАН',
    'Competences' => 'Чадварууд',
    'Conversation' => 'Харилцан яриа',
    'Conversation logging: DEPRECATED' => 'Харилцан ярианы лог: ХУУЧИРСАН',
    'Data' => 'Өгөгдөл',
    'Email' => 'Имэйл',
    'First name' => 'Нэр',
    'First name: DEPRECATED' => 'Нэр: ХУУЧИРСАН',
    'Gender' => 'Хүйс',
    'Gender: DEPRECATED' => 'Хүйс: ХУУЧИРСАН',
    'ID' => 'Ай-ди',
    'ID: DEPRECATED' => 'Ай-ди: ХУУЧИРСАН',
    'Language: DEPRECATED' => 'Хэл: ХУУЧИРСАН',
    'Last name' => 'Овог',
    'Last name: DEPRECATED' => 'Овог: ХУУЧИРСАН',
    'Locale' => 'Байршил',
    'Locations' => 'Байршлууд',
    'Materials' => 'Материалууд',
    'Meanings' => 'Агуулгууд',
    'Middle name' => 'Дундах нэр',
    'Middle name: DEPRECATED' => 'Дунд нэр: ХУУЧИРСАН',
    'Nationality' => 'Үндэс угсаа',
    'Nationality: DEPRECATED' => 'Үндэс угсаа: ХУУЧИРСАН',
    'Norms' => 'Хэм хэмжээ',
    'Occupation' => 'Мэргэжил',
    'Phone number' => 'Утасны дугаар',
    'Phone number: DEPRECATED' => 'Утасны дугаар: ХУУЧИРСАН',
    'Prefix name' => 'Урьтал нэр',
    'Prefix name: DEPRECATED' => 'Урьтал нэр: ХУУЧИРСАН',
    'Relationships' => 'Харилцаа',
    'Suffix name' => 'Дагавар нэр',
    'Suffix name: DEPRECATED' => 'Дагавар нэр: ХУУЧИРСАН',
    'Write data feed: DEPRECATED' => 'Өгөгдөл бичих: ХУУЧИРСАН',
];
