<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best,' => 'Хүндэтгэсэн,',
    'Check your email for further instructions.' => 'И-мэйлээ шалган дараагийн мэдээллүүдийг авна уу. Асуудал гарсан тохиолдолд СПАМ фолдерыг шалгана уу.',
    'Follow the link below to reset your password:' => 'Дараах холбоосоор нууц үгээ сэргээнэ үү:',
    'Follow the link below to verify your email:' => 'Дараах холбоосоор и-мэйлээ баталгаажуулна уу:',
    'Hello ' => 'Сайн уу',
    'If you forgot your password you can' => 'Нууц үгээ мартвал',
    'Need new verification email?' => 'Баталгаажуулах и-мэйл хэрэгтэй юу?',
    'Password does not match.' => 'Нууц үг тохирохгүй байна.',
    'Password successfully changed.' => 'Нууц үг амжилттай өөрчлөгдлөө.',
    'Please choose your new password' => 'Шинээр нууц үгээ оруулна уу',
    'Please fill out the following fields to login' => 'Дараах талбаруудыг бөглөн нэвтэрнэ үү',
    'Please fill out the following fields to signup' => 'Дараах талбаруудыг бөглөн бүртгүүлнэ үү',
    'Please fill out your email. A link to reset password will be sent there' => 'И-мэйл хаягаа оруулна уу. Нууц үг сэргээх холбоос илгээгдэх болно',
    'Please fill out your email. A verification email will be sent there' => 'И-мэйл хаягаа оруулна уу. Идэвхжүүлэх и-мэйл илгээгдэх болно',
    'Remember me' => 'Намайг сана',
    'Repeat password' => 'Нууц үгээ дахин оруул',
    'Resend' => 'Дахин илгээх',
    'Reset password' => 'Нууц үг сэргээх',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Уучлаарай, дараах и-мэйл хаягаар идэвхжүүлэх и-мэйл илгээх боломжгүй.',
    'Sorry, we are unable to verify your account with provided token.' => 'Уучлаарай, дараах токеноор таны аккаунтыг бататгах боломжгүй.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Бүртгүүлсэнд баярлалаа. И-мэйлээ шалган баталгаажуулна уу. Асуудал гарсан тохиолдолд СПАМ фолдерыг шалгана уу.',
    'The WeNet HUB Team' => 'Винэт HUB баг',
    'Verify account' => 'Аккаунт бататгах',
    'Your email has been confirmed!' => 'Таны и-мэйл баталгаажлаа!',
    'create an account' => 'шинэ аккаунт үүсгэх',
    'reset it' => 'сэргээх',
    'Please, accept our Privacy Policy.' => '',
    'privacy_consent1' => '',
    'privacy_consent2' => '',
];
