<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'App logic successfully deleted.' => '',
    'Attributes' => '',
    'Callbacks' => '',
    'Could not create new app logic.' => '',
    'Could not delete app logic.' => '',
    'Create a new app logic' => '',
    'INFO - Once you decide to set the app logic as a public one, a copy of the current app logic will be automatically created and you will be no more able to edit or delete it.' => '',
    'INFO - This app logic is no more editable or deletable because is public.' => '',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' => '',
    'Norms' => '',
    'Private' => '',
    'Public' => '',
    'Transactions' => '',
    'public app logic' => '',
];
